"""
Market analysis module for real estate data.

This module handles the merging of rental and sales data,
grouping comparables, and calculating market-wide yields.
"""

from typing import Dict, List, Tuple

import pandas as pd


class MarketAnalyzer:
    """Analyzer for market trends and yields."""
    
    def __init__(self, rentals_df: pd.DataFrame, sales_df: pd.DataFrame):
        """
        Initialize market analyzer.
        
        Args:
            rentals_df: DataFrame with rental listings
            sales_df: DataFrame with sales listings
        """
        self.rentals_df = rentals_df.copy()
        self.sales_df = sales_df.copy()
        
        # Ensure common columns exist
        self._preprocess_data()
        
    def _preprocess_data(self):
        """Standardize columns and extract features for grouping."""
        for df in [self.rentals_df, self.sales_df]:
            # Normalize 'district' to 'kerület'
            if 'district' in df.columns and 'kerület' not in df.columns:
                df.rename(columns={'district': 'kerület'}, inplace=True)

            if 'kerület' not in df.columns and 'location' in df.columns:
                 # Simple extraction fallback if not generated by preprocessor
                 df['kerület'] = df['location'].str.extract(r'(\w+)\. kerület').fillna('Unknown')
            
            # Normalize 'size_sqm' to 'area_m2'
            if 'size_sqm' in df.columns and 'area_m2' not in df.columns:
                df.rename(columns={'size_sqm': 'area_m2'}, inplace=True)

            # Simple size categorization
            if 'size_cat' not in df.columns and 'area_m2' in df.columns:
                df['size_cat'] = pd.cut(
                    df['area_m2'], 
                    bins=[0, 30, 45, 60, 80, 120, 999],
                    labels=['Mini (<30)', 'Kicsi (30-45)', 'Normál (45-60)', 'Közepes (60-80)', 'Nagy (80-120)', 'Luxus (>120)']
                )
                
            # Condition categorization fallback
            if 'condition_cat' not in df.columns and 'Állapot' in df.columns:
                df['condition_cat'] = df['Állapot'].fillna('Átlagos')

    def aggregate_market_data(self, group_by: List[str] = ['kerület', 'size_cat']) -> pd.DataFrame:
        """
        Aggregate data to find average prices and rents per group.
        
        Args:
            group_by: List of columns to group by
            
        Returns:
            DataFrame with aggregated market stats
        """
        # Aggregate Sales
        sales_agg = self.sales_df.groupby(group_by).agg(
            avg_sales_price=('price', 'mean'),
            avg_sales_price_m2=('price_per_m2', 'mean'),
            sales_count=('price', 'count')
        )
        
        # Aggregate Rentals
        rentals_agg = self.rentals_df.groupby(group_by).agg(
            avg_rent=('price', 'mean'),
            avg_rent_m2=('price_per_m2', 'mean'),
            rentals_count=('price', 'count')
        )
        
        # Merge
        market_summary = pd.merge(sales_agg, rentals_agg, left_index=True, right_index=True, how='inner')
        
        # Filter groups with enough data (relaxed for demo)
        market_summary = market_summary[
            (market_summary['sales_count'] >= 1) & 
            (market_summary['rentals_count'] >= 1)
        ]
        
        # Calculate Yields
        # Gross Yield = (Monthly Rent * 12) / Sales Price
        market_summary['gross_yield_percent'] = (market_summary['avg_rent'] * 12 / market_summary['avg_sales_price']) * 100
        
        # Price-to-Rent Ratio (Years to return investment)
        market_summary['price_to_rent_years'] = market_summary['avg_sales_price'] / (market_summary['avg_rent'] * 12)
        
        return market_summary.reset_index()

    def find_best_investment_areas(self, top_n: int = 10) -> pd.DataFrame:
        """Find the best areas/categories by yield."""
        summary = self.aggregate_market_data()
        return summary.sort_values('gross_yield_percent', ascending=False).head(top_n)
